Repository mcci-catena/Arduino_Core_STM32, pull requests merged in 2019-07, with the labels that each got.

#98 Issue95 - Added USB + HW serial support for 4630 and 461x boards
  boards.json
  boards.template
  boards.txt
  cores/arduino/HardwareSerial.cpp
  cores/arduino/stm32/usb_serial.h
  variants/CATENA_4551/variant.h
  variants/CATENA_461x/variant.h
  variants/CATENA_4630/PeripheralPins.c
  variants/CATENA_4630/variant.h
  variants/CATENA_4801/PeripheralPins.c
  variants/CATENA_4801/variant.h
  variants/mcci_common_uart.h
Labels: enhancement

#102 Fix #97: document 4617, 4618, 4630, improve comparison chart
  README.md
Labels: docs

#105 Fixed warnings when compile C file and fixed errors when no serial build
  cores/arduino/stm32/null_serial.cpp
  variants/mcci_common_uart.h
Labels: bug

#109 Fix #108: range is SysTick->LOAD + 1
  cores/arduino/stm32/clock.c
  cores/arduino/wiring_time.h
Labels: bug

#107 Set up RTC clock with LSE clock and change clock calibration value
  variants/CATENA_4551/variant.cpp
  variants/CATENA_461x/variant.cpp
  variants/CATENA_4630/variant.cpp
  variants/CATENA_4801/variant.cpp
Labels: bug

#112 Fix #79: refactor to centralize code that was replicated in variants
  cores/arduino/stm32/USB/usbd_cdc.c
  cores/arduino/stm32/USB/usbd_cdc.h
  cores/arduino/stm32/USB/usbd_cdc_desc.c
  cores/arduino/stm32/USB/usbd_cdc_desc.h
  cores/arduino/stm32/USB/usbd_cdc_if.c
  cores/arduino/stm32/USB/usbd_cdc_if.h
  cores/arduino/stm32/USB/usbd_conf.c
  cores/arduino/stm32/USB/usbd_conf.h
  cores/arduino/stm32/USB/usbd_desc.c
  cores/arduino/stm32/USB/usbd_desc.h
  cores/arduino/stm32/override_hal_gettick.c
  cores/arduino/stm32/systemclock_config.cpp
  cores/arduino/stm32/usb_interface.h
  cores/arduino/stm32/yield.c
  platform.txt
  variants/CATENA_4551/override_usbd_ll_connectionstate.c
  variants/CATENA_4551/usb/usbd_conf.h
  variants/CATENA_4551/variant.cpp
  variants/CATENA_461x/override_usbd_ll_connectionstate.c
  variants/CATENA_461x/usb/usbd_cdc.c
  variants/CATENA_461x/usb/usbd_cdc.h
  variants/CATENA_461x/usb/usbd_cdc_desc.c
  variants/CATENA_461x/usb/usbd_cdc_desc.h
  variants/CATENA_461x/usb/usbd_cdc_if.c
  variants/CATENA_461x/usb/usbd_cdc_if.h
  variants/CATENA_461x/usb/usbd_conf.c
  variants/CATENA_461x/usb/usbd_desc.c
  variants/CATENA_461x/usb/usbd_desc.h
  variants/CATENA_461x/variant.cpp
  variants/CATENA_4630/override_usbd_ll_connectionstate.c
  variants/CATENA_4630/usb/usbd_cdc.c
  variants/CATENA_4630/usb/usbd_cdc.h
  variants/CATENA_4630/usb/usbd_cdc_desc.c
  variants/CATENA_4630/usb/usbd_cdc_desc.h
  variants/CATENA_4630/usb/usbd_cdc_if.c
  variants/CATENA_4630/usb/usbd_cdc_if.h
  variants/CATENA_4630/usb/usbd_conf.c
  variants/CATENA_4630/usb/usbd_conf.h
  variants/CATENA_4630/usb/usbd_desc.c
  variants/CATENA_4630/usb/usbd_desc.h
  variants/CATENA_4630/variant.cpp
  variants/CATENA_4801/variant.cpp
Labels: enhancement

#116 Fix #115: prepare for release
  README.md
  cores/arduino/Arduino.h
  platform.txt
Labels: release
